python -m experimental.main  --learning-rate 0.000025 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000050 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000250 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000500 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf

python -m experimental.main  --learning-rate 0.000001 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000010 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000100 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.001000 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.001_te_0.01_l1_1.0_l2_0.0_ty_11_ba_64.tf


python -m experimental.main  --learning-rate 0.000025 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000050 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000250 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000500 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf

python -m experimental.main  --learning-rate 0.000001 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000010 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000100 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.001000 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_0.1_ty_11_ba_64.tf


python -m experimental.main  --learning-rate 0.000025 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000050 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000250 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000500 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf

python -m experimental.main  --learning-rate 0.000001 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000010 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000100 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.001000 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_1.0_l2_1.0_ty_11_ba_64.tf


python -m experimental.main  --learning-rate 0.000025 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000050 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000250 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000500 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf

python -m experimental.main  --learning-rate 0.000001 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000010 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000100 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.001000 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.1_l1_0.1_l2_1.0_ty_11_ba_64.tf


python -m experimental.main  --learning-rate 0.000025 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000050 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000250 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000500 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf

python -m experimental.main  --learning-rate 0.000001 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000010 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.000100 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf
python -m experimental.main  --learning-rate 0.001000 --batch-size 64 --num-augment 8 --out-dir modeldir/supervised/ --pair-csv dataset/supervised/fileNames.txt --model-type 11 --data-dir dataset/supervised/image/ --label-dir dataset/supervised/mask/  --weight-file modeldir/unsupervised/model_best_lr_0.0001_te_0.01_l1_0.0_l2_1.0_ty_11_ba_64.tf